### PR TITLE
Adding Carthage support.

### PR DESCRIPTION
**Pull request by danielmartinprieto**

### CODE REVIEW

**Comment by iluuu1994** [comment]
Awesome! :metal:

**Comment by danielmartinprieto** [comment]
@iluuu1994 maybe you want to add a release tag so Carthage works better. I didn't know exactly in which state the project is (0.X, 1.X, alpha, beta...) so I didn't do it. More info:
https://github.com/Carthage/Carthage#tag-stable-releases

**Comment by iluuu1994** [comment]
There you go, I created a 1.0 tag.

**Comment by danielmartinprieto** [comment]
:+1:

**Pull request merged**
